### PR TITLE
Add OpenGraph annotations

### LINKED ISSUE #33: Add Open Graph Attributes for blog posts
These are what is used by fb and other sites to provide large image previews. We should be adding this info into the header of these pages so the preview looks good.

Reference: https://ogp.me

### PR DESCRIPTION
**Pull request by lenary**
Also, refactor header contents

Fixes #33 

I need to check all the pages (especially the front page), but this should be correct.

### CODE REVIEW

**Comment by imphil** [comment]
@lenary what's the status of this one? Should we take it as-is?

**Comment by lenary** [comment]
It's waiting on a "social header" image before I do final polish, unless you think we should go without for the moment.

**Comment by imphil** [comment]
Let's do without it for now.

**Comment by imphil** [comment]
I picked the Google Analytics-related parts from this PR and pushed it to master.

**Pull request closed without merging**
